name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install
        uses: actions/setup-node@v4
        with:
          node-version: '20.8.1'

      - run: yarn install

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

